### ISSUE TITLE
Automated Testing Sim Error (7/5/2016 9:58 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#347]
```
Error: Module name "BENDING_LIGHT/bendingLight" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at Object.localRequire [as require] (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1392:30)
    at requirejs (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1737:20)
    at http://phettest.colorado.edu/bending-light/js/common/view/FloatingLayout.js?bust=1467734868024:13:22
    at Object.execCb (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.check (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:866:35)
    at Object.enable (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1143:14)
    at Object.init (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1170:55)
    at Object.completeLoad (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1544:11)
```

**Comment by samreid** [comment]
Tests OK in my canary:

![image](https://cloud.githubusercontent.com/assets/679486/16591660/20fe29fc-429a-11e6-8770-e95748b5a36f.png)

**Comment by samreid** [comment]
Runs OK in my mac chrome and mac firefox too.  Can you provide more details as to how/where it failed?

**Comment by samreid** [comment]
I tried running from phettest "Automated Tests" and saw this:

![image](https://cloud.githubusercontent.com/assets/679486/16592665/011c3f20-429f-11e6-81a0-d3694c83be75.png)

@phet-steele can you reproduce the problem reliably?

**Comment by phet-steele** [comment]
@samreid I did not get it a second time.

**Comment by samreid** [comment]
Perhaps a spurious requirejs loading issue, I'll close and we can reopen if it recurs.

**Comment by phet-steele** [comment]
@samreid this has reoccurred on the 7/12 automated testing.

**Comment by samreid** [comment]
Perhaps I can investigate this as we work toward #351, unassigning until then.

**Comment by samreid** [comment]
Perhaps on a slower computer or throttled connection we could trigger the not yet loaded problem?

**Comment by samreid** [comment]
I throttled at 3G and despite taking about 30 seconds to launch, there were no errors like above. I wonder if I eliminate FloatingLayout.js as in the stack above, if the problem would disappear.  This is happening in #348

**Comment by samreid** [comment]
Found the likely culprit and amended it above.  This seems likely enough to be the issue that I'm inclined to close the issue, but @phet-steele please re-open if it recurs in a subsequent weekly test.
