### ISSUE TITLE
CT Error: Unable to read "../bending-light/js/phet-io/bending-light-phet-io-elements-baseline.js"

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#391]
```
bending-light : build : phet-io
Failure to grunt snapshot-1584510864080-phet-io/bending-light:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (bending-light, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 6484ms
>> Production minification complete: 33322ms (2502475 bytes)
>> Debug minification complete: 0ms (6381234 bytes)
Building brand: phet-io
>> Webpack build complete: 3750ms
Fatal error: Perennial task failed:
Error: Unable to read "../bending-light/js/phet-io/bending-light-phet-io-elements-baseline.js" file (Error code: ENOENT).
  at Object.util.error (/data/share/phet/continuous-testing/snapshot-1584510864080-phet-io/chipper/node_modules/grunt-legacy-util/index.js:55:39)
  at Object.file.read (/data/share/phet/continuous-testing/snapshot-1584510864080-phet-io/chipper/node_modules/grunt/lib/grunt/file.js:225:22)
  at getPreloads.map.filename (/data/share/phet/continuous-testing/snapshot-1584510864080-phet-io/chipper/js/grunt/buildRunnable.js:164:69)
  at Array.map (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1584510864080-phet-io/chipper/js/grunt/buildRunnable.js:164:41)

Full Error details:
{
  "origError": {
    "errno": -2,
    "syscall": "open",
    "code": "ENOENT",
    "path": "../bending-light/js/phet-io/bending-light-phet-io-elements-baseline.js"
  }
}


Approximately 3/17/2020, 11:54:24 PM
bending-light : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584510864080/phet-io-wrappers/phet-io-wrappers-tests.html?sim=bending-light&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 3/17/2020, 11:54:24 PM
bending-light : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584510864080/phet-io-wrappers/phet-io-wrappers-tests.html?sim=bending-light
9 out of 9 tests passed. 0 failed.

Approximately 3/17/2020, 11:54:24 PM
```

**Comment by samreid** [comment]
Should be fixed by https://github.com/phetsims/bending-light/commit/f966c41ef13f617007eb09e5839f98428da16243, closing.
