### ISSUE TITLE
CT PhET-iO API error

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#392]
```
bending-light : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/bending-light/bending-light_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584609658817:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/bending-light/bending-light_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584609658817:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io-wrappers/mirror-inputs/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584600800566:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io-wrappers/mirror-inputs/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584623806278:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584597600498:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584597600505:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584612057568:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584612057577:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/studio/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584601684049:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/studio/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584615095455:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
bending-light : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/studio/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
bendingLight.introScreen.bottomMediumProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/assert/js/assert.js?bust=1584625523016:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/tandem/js/phetioAPIValidation.js:106:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/joist/js/Sim.js:842:48
id: Bayes Chrome
```

**Comment by KatieWoe** [comment]
May be related:
```
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed phetioType validator: [object Object]
Error: Assertion failed: value failed phetioType validator: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584929055835:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/ValidatorDef.js:305:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/validate.js:27:18)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:138:32)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/PropertyIO.js:116:16)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:247:22)
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed phetioType validator: [object Object]
Error: Assertion failed: value failed phetioType validator: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584949403256:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/ValidatorDef.js:305:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/validate.js:27:18)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:138:32)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/PropertyIO.js:116:16)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:247:22)
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed phetioType validator: [object Object]
Error: Assertion failed: value failed phetioType validator: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584965729229:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/ValidatorDef.js:305:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/validate.js:27:18)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:138:32)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/PropertyIO.js:116:16)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:247:22)
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed phetioType validator: [object Object]
Error: Assertion failed: value failed phetioType validator: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584973539454:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/ValidatorDef.js:305:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/validate.js:27:18)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:138:32)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/axon/js/PropertyIO.js:116:16)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:247:22)
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
bending-light : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/phet-io-wrappers-tests.html?sim=bending-light&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 3/22/2020, 5:53:10 PM
bending-light : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/phet-io-wrappers-tests.html?sim=bending-light
9 out of 9 tests passed. 0 failed.

Approximately 3/22/2020, 5:53:10 PM
```

**Comment by samreid** [comment]
This error hasn't occurred on CT for a while, closing.
