### ISSUE TITLE
CT failed phetioType validator

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#393]
```
bending-light : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io-wrappers/state/?sim=bending-light&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed phetioType validator: [object Object]
Error: Assertion failed: value failed phetioType validator: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/ValidatorDef.js:305:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/validate.js:27:18)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:138:32)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/PropertyIO.js:116:16)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/PhetioStateEngine.js:247:22)
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
bending-light : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io-wrappers/phet-io-wrappers-tests.html?sim=bending-light&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 4/12/2020, 7:49:56 PM
bending-light : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io-wrappers/phet-io-wrappers-tests.html?sim=bending-light
9 out of 9 tests passed. 0 failed.

Approximately 4/12/2020, 7:49:56 PM
```

**Comment by samreid** [comment]
This error hasn't occurred on CT for a while, closing.
