### ISSUE TITLE
CT text should be a string or number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#402]
```
bending-light : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633950904767%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at MoreToolsModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at MoreToolsModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:177:30)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM

----------------------------------

bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633964252881%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at MoreToolsModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at MoreToolsModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:177:30)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM

----------------------------------

bending-light : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633953725425%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at IntroModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at IntroModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:177:30)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM

----------------------------------

bending-light : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633953466274%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at MoreToolsModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at MoreToolsModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:177:30)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM

----------------------------------

bending-light : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633954744706%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at IntroModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at IntroModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:133:38)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM

----------------------------------

bending-light : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/phet-io-wrappers/mirror-inputs/?sim=bending-light&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633953106594%7D
Uncaught Error: Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at MoreToolsModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at MoreToolsModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:177:30)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM

----------------------------------

bending-light : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1633948997184%22%2C%22timestamp%22%3A1633955737252%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/assert/js/assert.js:25:13)
at Text.setText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/scenery/js/nodes/Text.js:100:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/view/IntensityMeterNode.js:90:23
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/TinyEmitter.js:65:17)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:222:27)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/axon/js/Property.js:147:22)
at IntensityMeter.updateReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:94:34)
at IntensityMeter.addRayReading (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/common/model/IntensityMeter.js:70:14)
at MoreToolsModel.addAndAbsorb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:227:33)
at MoreToolsModel.propagateRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1633948997184/chipper/dist/bending-light/js/intro/model/IntroModel.js:155:26)
id: Bayes Chrome
Snapshot from 10/11/2021, 4:43:17 AM
```

**Comment by samreid** [comment]
Fixed, thanks for the report, closing.
