### ISSUE TITLE
CT Cannot read properties of null (reading 'notePendingRemoval')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#412]
```
bending-light : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'notePendingRemoval')
TypeError: Cannot read properties of null (reading 'notePendingRemoval')
at Au.notePendingRemoval (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:947804)
at Au.stitch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:950543)
at fu.stitch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:960316)
at Fu.groupSyncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:990039)
at Fu.syncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:986974)
at Fu.localSyncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:987230)
at Fu.syncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:986952)
at Fu.localSyncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:987230)
at Fu.syncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:986952)
at Fu.baseSyncTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/build/phet/bending-light_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674136773743%7D&fuzz&memoryLimit=1000:963:986294)
id: Bayes Puppeteer
Snapshot from 1/19/2023, 5:02:36 AM

----------------------------------

bending-light : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674134009108%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: reentry detected, value=Vector2(0.00003329122829861112, -0.0000020725027126736145), oldValue=Vector2(0.000022988622504340282, 7.538758680555542e-7)
Error: Assertion failed: reentry detected, value=Vector2(0.00003329122829861112, -0.0000020725027126736145), oldValue=Vector2(0.000022988622504340282, 7.538758680555542e-7)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:6)
at reposition (DragListener.ts:305:15)
at apply (PhetioAction.ts:157:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:895:13)
id: Bayes Puppeteer
Snapshot from 1/19/2023, 5:02:36 AM

----------------------------------

bending-light : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674129756648%22%2C%22timestamp%22%3A1674134230606%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674129756648/assert/js/assert.js:28:13)
at assert (Node.ts:917:14)
at removeChild (PrismsScreenView.ts:164:17)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:125:21)
at emit (createObservableArray.ts:309:57)
at pop (createObservableArray.ts:394:46)
at clear (PrismsModel.ts:431:23)
at clear (PrismNode.ts:124:18)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 1/19/2023, 5:02:36 AM
```

**Comment by samreid** [comment]
This may be fixed, or very rare.  Closing.
